site_name: Spektral
theme:
    name: 'readthedocs'
    custom_dir: 'sources/custom_theme/'
    highlightjs: true


docs_dir: sources
repo_url: 'https://github.com/danielegrattarola/spektral/'
edit_uri: 'edit/master/docs/sources'
site_author: Daniele Grattarola
site_description: 'Spektral: a Framework for Relational Representation Learning'
google_analytics:
    - UA-125823175-1
    - auto

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML'

markdown_extensions:
    - mdx_math

nav:
- Home: index.md
- Data representation: data.md
- Layers:
    - Convolutional Layers: layers/convolution.md
    - Base Layers: layers/base.md
    - Pooling Layers: layers/pooling.md
- Datasets:
    - Citation: datasets/citation.md
    - Delaunay: datasets/delaunay.md
    - QM9: datasets/qm9.md
    - MNIST: datasets/mnist.md
- Chemistry: chem.md
- Brain: brain.md
- Utils:
    - Input/Ouput: utils/io.md
    - Conversion: utils/conversion.md
    - Convolution: utils/convolution.md
    - Miscellaneous: utils/misc.md
    - Plotting: utils/plotting.md
- About:
    - Acknowledgements: acknowledgements.md
    - Featured papers: papers.md
